spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/ufmsos
    username: postgres
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG

server:
  port: 8080

app:
  security:
    jwt:
      secret: 5a57afc4b448c0289f736c9dbf82c4963d2274c362bd633813c4d391834e7ead
      expiration: 86400000 # 24h
