services:
  ufmsos-db:
    image: postgres:17-alpine
    container_name: ufmsos-db
    environment:
      POSTGRES_DB: ufmsos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./database/schema_inicial.sql:/docker-entrypoint-initdb.d/schema_inicial.sql
    networks:
      - ufmsos-network

  ufmsos-mq:
    image: rabbitmq:4-management-alpine
    container_name: ufmsos-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - ufmsos-network

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - ufmsos-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8080" # Porta externa 8000 para o Gateway
    environment:
      EUREKA_HOST: eureka-server
    depends_on:
      - eureka-server
    networks:
      - ufmsos-network

  ms-auth:
    build: ./auth-service
    container_name: ms-auth
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ufmsos-db:5432/ufmsos
      DB_PASSWORD: postgres
      EUREKA_HOST: eureka-server
    depends_on:
      - ufmsos-db
      - eureka-server
    networks:
      - ufmsos-network

  ms-estudos:
    build: ./estudos-service
    container_name: ms-estudos
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ufmsos-db:5432/ufmsos
      DB_PASSWORD: postgres
      EUREKA_HOST: eureka-server
    depends_on:
      - ufmsos-db
      - eureka-server
    networks:
      - ufmsos-network

  ms-financeiro:
    build: ./financeiro-service
    container_name: ms-financeiro
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ufmsos-db:5432/ufmsos
      DB_PASSWORD: postgres
      EUREKA_HOST: eureka-server
    depends_on:
      - ufmsos-db
      - eureka-server
    networks:
      - ufmsos-network

  ms-estagio:
    build: ./estagio-service
    container_name: ms-estagio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ufmsos-db:5432/ufmsos
      DB_PASSWORD: postgres
      EUREKA_HOST: eureka-server
    depends_on:
      - ufmsos-db
      - eureka-server
    networks:
      - ufmsos-network

  ms-saude:
    build: ./saude-service
    container_name: ms-saude
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ufmsos-db:5432/ufmsos
      DB_PASSWORD: postgres
      EUREKA_HOST: eureka-server
    depends_on:
      - ufmsos-db
      - eureka-server
    networks:
      - ufmsos-network

  ms-rotina:
    build: ./rotina-service
    container_name: ms-rotina
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ufmsos-db:5432/ufmsos
      DB_PASSWORD: postgres
      EUREKA_HOST: eureka-server
    depends_on:
      - ufmsos-db
      - eureka-server
    networks:
      - ufmsos-network

  ms-curriculo:
    build: ./curriculo-service
    container_name: ms-curriculo
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ufmsos-db:5432/ufmsos
      DB_PASSWORD: postgres
      EUREKA_HOST: eureka-server
    depends_on:
      - ufmsos-db
      - eureka-server
    networks:
      - ufmsos-network

  ms-ia:
    build: ./ia-service
    container_name: ms-ia
    environment:
      SPRING_RABBITMQ_HOST: ufmsos-mq
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      EUREKA_HOST: eureka-server
    depends_on:
      - ufmsos-mq
      - eureka-server
    networks:
      - ufmsos-network

networks:
  ufmsos-network:
    driver: bridge
