spring:
  application:
    name: financeiro-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/ufmsos
    username: postgres
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8082
