spring:
  application:
    name: estudos-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ufmsos
    username: postgres
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081
